version: "3.8"

#TODO: switch to bridge network for other services to use
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    networks:
      - default
    expose:
      - 4566
      - 4571
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
#TODO: make sure to add env var for data file
  rqg-service:
    build: .
    volumes:
      - "./data/:/data"
    links:
      - "localstack:rsq-aws"
    depends_on:
      - localstack
    networks:
      - default

