version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=open-ocean
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    container_name: "open-ocean-api"
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=open-ocean
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: on-failure
    depends_on:
      - db
volumes:
  db-data:
    driver: local